# Generated by Django 4.2.30 on 2026-07-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_stockreceiptbatch_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceiptbatch',
            name='additional_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
