# Generated by Django 4.2.30 on 2026-07-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockreceiptbatch_additional_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='adjustment_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockreceiptbatch',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
