# Generated by Django 4.2.30 on 2026-07-10 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='APEX CARE IR', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('tax_information', models.CharField(blank=True, max_length=255)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('invoice_footer_text', models.TextField(blank=True, default='Thank you for choosing Apex Care IR. For support, contact us anytime.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company settings',
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('include_year', models.BooleanField(default=False)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('last_year', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=40)),
                ('reference_number', models.CharField(db_index=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('adjusted', 'Adjusted'), ('cancelled', 'Cancelled'), ('issued', 'Issued'), ('emailed', 'Emailed'), ('regenerated', 'Regenerated')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'reference_number'], name='common_tran_module_65843a_idx'), models.Index(fields=['reference_id'], name='common_tran_referen_9e90fd_idx')],
            },
        ),
    ]
