# Generated by Django 4.2.30 on 2026-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('adjusted', 'Adjusted'), ('cancelled', 'Cancelled'), ('issued', 'Issued'), ('emailed', 'Emailed'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('regenerated', 'Regenerated')], max_length=20),
        ),
    ]
