# Generated by Django 4.2.30 on 2026-06-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_status_cceeb8_idx',
            old_name='appointmen_status_227b07_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_preferr_9da5db_idx',
            old_name='appointmen_preferr_5f14f9_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_full_na_fc0bef_idx',
            old_name='appointmen_full_na_4fd5c2_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_phone_n_c8dbe7_idx',
            old_name='appointmen_phone_n_0bdfd0_idx',
        ),
    ]
