# Generated by Django 4.2.30 on 2026-07-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='business_area',
            field=models.CharField(choices=[('clinic', 'Clinic / IR Services'), ('website', 'Website & Digital'), ('shared', 'Shared / General')], default='shared', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('website_hosting', 'Website & Hosting'), ('marketing', 'Marketing & Advertising'), ('utilities', 'Utilities'), ('rent', 'Rent & Facilities'), ('transport', 'Transport & Logistics'), ('supplies', 'Office & Supplies'), ('inventory', 'Inventory Purchases'), ('payroll', 'Payroll & Salaries'), ('insurance', 'Insurance'), ('licenses', 'Licenses & Compliance'), ('maintenance', 'Maintenance & Repairs'), ('professional', 'Professional Services'), ('taxes', 'Taxes & Fees'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type'], name='finance_exp_expense_f68925_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business_area'], name='finance_exp_busines_686ac2_idx'),
        ),
    ]
