# Generated by Django 4.2.30 on 2026-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_expense_number_payroll_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
