# Generated by Django 4.2.30 on 2026-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
