# Generated by Django 4.2.30 on 2026-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidebar_navigation_mode',
            field=models.CharField(choices=[('accordion', 'Accordion'), ('multi_expand', 'Multi-Expand')], default='accordion', max_length=20),
        ),
    ]
