CATALOGUE_BY_CATEGORY = {
    "Interventional Radiology": [
        "Haemodialysis Catheter",
        "PICC Line",
        "Central Venous Catheter",
        "Drainage Catheter",
        "Introducer Sheath",
        "Guidewire",
        "Angiographic Catheter",
        "Balloon Catheter",
        "Embolization Coil",
        "Microcatheter",
        "Biopsy Needle",
    ],
    "Imaging Equipment": [
        "Ultrasound Machine",
        "C-arm",
        "Digital X-ray",
        "CT Injector",
        "Contrast Warmer",
    ],
    "Patient Monitoring": [
        "Patient Monitor",
        "ECG Machine",
        "Pulse Oximeter",
        "Defibrillator",
        "Infusion Pump",
        "Syringe Pump",
    ],
    "Surgical Equipment": [
        "Operating Table",
        "Surgical Lights",
        "Suction Machine",
        "Electrosurgical Unit",
    ],
    "Surgical Instruments": [
        "Magill Forceps",
        "Tongue Blade - Size 2",
        "Tongue Blade - Size 3",
        "Tongue Blade - Size 4",
        "Stylet",
        "Morrison Pillar Retractor",
        "Towel Dissector and Pillar Retractor",
        "Bozeman Forceps",
        "Boyle-Davis Mouth Gag",
        "Excision Set",
        "Incision Set",
        "General Set",
        "C/S (Caesarean Section) Set",
        "Instrument Trays",
        "Kidney Dish",
        "Long Needle Holder",
        "Small Artery Forceps",
        "Basic Paediatric Set",
    ],
    "Consumables": [
        "Gloves",
        "Syringes",
        "IV Cannulas",
        "Dressings",
        "Gauze",
        "Needles",
        "Surgical Gowns",
        "Foley Catheters",
        "Nasogastric Tube (Adult)",
        "Nasogastric Tube (Paediatric)",
        "Suction Catheters",
        "Urine Bags",
        "Gauze Swabs",
        "IV Giving Sets",
    ],
    "Furniture": [
        "Hospital Bed",
        "Bedside Locker",
        "Overbed Table",
        "Wheelchair",
        "Stretcher",
    ],
    "Laboratory Equipment": [
        "Centrifuge",
        "Microscope",
        "Chemistry Analyzer",
        "Hematology Analyzer",
    ],
    "Dialysis Equipment": [
        "Dialysis Machine",
        "Dialyzer",
        "Blood Tubing Set",
        "Dialysis Concentrate",
    ],
}

CATALOGUE_UNIT_OVERRIDES = {
    "Boyle-Davis Mouth Gag": "set",
    "Excision Set": "set",
    "Incision Set": "set",
    "General Set": "set",
    "C/S (Caesarean Section) Set": "set",
    "Basic Paediatric Set": "set",
}
