import io
from decimal import Decimal
from typing import Optional

from django.core.files.base import ContentFile
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from apps.common.models import CompanySettings
from apps.common.services.company_branding import get_company_branding, get_company_logo_path, invoice_contact_lines


def _money(value):
    return f"KES {Decimal(value or 0):,.2f}"


def build_invoice_pdf_bytes(*, invoice, sale, company: Optional[CompanySettings] = None):
    company = company or CompanySettings.get_solo()
    branding = get_company_branding()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=1.5 * cm, rightMargin=1.5 * cm, topMargin=1.5 * cm, bottomMargin=1.5 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=18, textColor=colors.HexColor("#6E2C3E"))
    muted_style = ParagraphStyle("Muted", parent=styles["Normal"], fontSize=9, textColor=colors.grey)
    normal = styles["Normal"]

    story = []
    logo_path = branding.get("logo_path") or get_company_logo_path(company)
    if logo_path:
        try:
            from reportlab.platypus import Image

            story.append(Image(logo_path, width=3.5 * cm, height=1.75 * cm))
            story.append(Spacer(1, 0.2 * cm))
        except Exception:
            pass

    story.extend([
        Paragraph(branding["company_name"], title_style),
        Paragraph(company.address or branding.get("address") or "", normal),
        Paragraph(
            " | ".join(
                filter(
                    None,
                    [
                        branding["email"],
                        branding["phone"],
                        branding.get("website"),
                    ],
                )
            ),
            muted_style,
        ),
        Spacer(1, 0.4 * cm),
        Paragraph(f"<b>INVOICE</b> {invoice.invoice_number}", styles["Heading2"]),
        Paragraph(f"Invoice Date: {invoice.invoice_date}", normal),
        Paragraph(
            f"Generated By: {(invoice.generated_by.get_full_name() or invoice.generated_by.email) if invoice.generated_by else 'System'}",
            normal,
        ),
        Spacer(1, 0.3 * cm),
    ])

    bill_to_header = Table(
        [[Paragraph("<b>Bill To</b>", normal), ""]],
        colWidths=[10 * cm, 6 * cm],
    )
    story.append(bill_to_header)

    customer_logo_cell = ""
    if invoice.customer and invoice.customer.logo:
        try:
            from reportlab.platypus import Image

            customer_logo_cell = Image(invoice.customer.logo.path, width=2.5 * cm, height=1.5 * cm)
        except Exception:
            customer_logo_cell = ""

    customer_lines = [
        Paragraph(invoice.customer_name, normal),
    ]
    if invoice.customer_company:
        customer_lines.append(Paragraph(invoice.customer_company, normal))
    if invoice.customer_phone:
        customer_lines.append(Paragraph(f"Phone: {invoice.customer_phone}", normal))
    if invoice.customer_email:
        customer_lines.append(Paragraph(f"Email: {invoice.customer_email}", normal))
    if invoice.customer_address:
        customer_lines.append(Paragraph(invoice.customer_address, normal))

    if customer_logo_cell:
        bill_to_table = Table(
            [[customer_lines, customer_logo_cell]],
            colWidths=[10 * cm, 6 * cm],
        )
        story.append(bill_to_table)
    else:
        story.extend(customer_lines)

    story.append(Spacer(1, 0.5 * cm))

    line_items = list(invoice.line_items.select_related("product").all())
    table_data = [["#", "Product", "SKU", "Qty", "Unit Price", "Discount", "Line Total"]]
    if line_items:
        for index, item in enumerate(line_items, start=1):
            table_data.append(
                [
                    str(index),
                    item.product.name,
                    item.product.sku,
                    str(item.quantity),
                    _money(item.unit_price),
                    _money(item.discount),
                    _money(item.line_total),
                ]
            )
    else:
        line_total = Decimal(sale.quantity) * sale.price
        table_data.append(
            [
                "1",
                sale.product.name,
                sale.product.sku,
                str(sale.quantity),
                _money(sale.price),
                _money(sale.discount),
                _money(line_total),
            ]
        )
    table = Table(table_data, colWidths=[1 * cm, 5.5 * cm, 2.5 * cm, 1.2 * cm, 2.5 * cm, 2.2 * cm, 2.5 * cm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6E2C3E")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("ALIGN", (3, 1), (-1, -1), "RIGHT"),
            ]
        )
    )
    story.extend([table, Spacer(1, 0.4 * cm)])

    summary = [
        ["Subtotal", _money(invoice.subtotal)],
        ["Discount", _money(invoice.discount)],
        ["Tax", _money(invoice.tax)],
        ["Grand Total", _money(invoice.grand_total)],
        ["Amount Paid", _money(getattr(invoice, "amount_paid", 0))],
        ["Balance Due", _money(invoice.balance_due if hasattr(invoice, "balance_due") else invoice.grand_total)],
        ["Payment Status", invoice.get_payment_status_display()],
        ["Invoice Status", invoice.get_status_display()],
    ]
    summary_table = Table(summary, colWidths=[5 * cm, 5 * cm], hAlign="RIGHT")
    summary_table.setStyle(TableStyle([("ALIGN", (1, 0), (1, -1), "RIGHT"), ("FONTNAME", (0, -2), (-1, -2), "Helvetica-Bold")]))
    story.extend([summary_table, Spacer(1, 0.6 * cm)])

    footer = branding["invoice_footer_text"] or company.invoice_footer_text or "Thank you for your business."
    story.append(Paragraph(footer, normal))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph("<b>Contact Us</b>", normal))
    for line in invoice_contact_lines(branding):
        story.append(Paragraph(line, muted_style))
    story.append(
        Paragraph(
            f"Generated: {timezone.localtime().strftime('%Y-%m-%d %H:%M')} | Ref: {invoice.invoice_number}",
            muted_style,
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


def save_invoice_pdf(invoice, sale):
    pdf_bytes = build_invoice_pdf_bytes(invoice=invoice, sale=sale)
    filename = f"{invoice.invoice_number}.pdf"
    invoice.pdf_file.save(filename, ContentFile(pdf_bytes), save=True)
    invoice.pdf_generated_at = timezone.now()
    invoice.save(update_fields=["pdf_generated_at", "updated_at"])
    return invoice.pdf_file
