# Generated by Django 4.2.30 on 2026-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_invoice_sale_created_by_sale_sale_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
