# Generated by Django 4.2.30 on 2026-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
